config/routes.rb
Rails.application.routes.draw do
  resources :library_books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'library_books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library_book.rb
class LibraryBook < ApplicationRecord

  broadcasts_to -> (library_book) { 'library_books' }, target: :library_books, inserts_by: :prepend
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/library_books_controller.rb
class LibraryBooksController < ApplicationController
  before_action :set_library_book, only: %i[ show edit update destroy ]

  # GET /library_books or /library_books.json
  def index
    @library_books = LibraryBook.all
  end

  # GET /library_books/1 or /library_books/1.json
  def show
  end

  # GET /library_books/new
  def new
    @library_book = LibraryBook.new
  end

  # GET /library_books/1/edit
  def edit
  end

  # POST /library_books or /library_books.json
  def create
    @library_book = LibraryBook.new(library_book_params)

    respond_to do |format|
      if @library_book.save
        format.html { redirect_to @library_book, notice: "Library book was successfully created." }
        format.json { render :show, status: :created, location: @library_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /library_books/1 or /library_books/1.json
  def update
    respond_to do |format|
      if @library_book.update(library_book_params)
        format.html { redirect_to @library_book, notice: "Library book was successfully updated." }
        format.json { render :show, status: :ok, location: @library_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /library_books/1 or /library_books/1.json
  def destroy
    @library_book.destroy
    respond_to do |format|
      format.html { redirect_to library_books_url, notice: "Library book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library_book
      @library_book = LibraryBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_book_params
      params.require(:library_book).permit(:title, :status, :description, :status_date, :internal_info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/library_books_helper.rb
module LibraryBooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwired</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/library_books/_form.html.erb
<%= form_with(model: library_book) do |form| %>
  <% if library_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library_book.errors.count, "error") %> prohibited this library_book from being saved:</h2>

      <ul>
        <% library_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :status_date %>
    <%= form.datetime_select :status_date %>
  </div>

  <div class="field">
    <%= form.label :internal_info %>
    <%= form.text_area :internal_info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/library_books/_library_book.html.erb
<%= turbo_frame_tag library_book do %>
<div class="card card-body">
  <div class="col">
    <%= library_book.title %>
  </div>
  <div class="col">
    <%= library_book.status&.titleize %>
  </div>
  <div class="col">
    <%= library_book.status_date %>
  </div>
  <div class="col">
    <%= link_to library_book.title, library_book, 'data-turbo-frame': '_top' %>
  </div>
</div>
<%end%>

app/views/library_books/edit.html.erb
<h1>Editing Library Book</h1>

<%= render 'form', library_book: @library_book %>

<%= link_to 'Show', @library_book %> |
<%= link_to 'Back', library_books_path %>

app/views/library_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Library Books</h1>

<%= turbo_stream_from "library_books" %>
<%=turbo_frame_tag "library_books" do %>
  <%= render @library_books %>
<%end%>

<br>

<%= link_to 'New Library Book', new_library_book_path %>

app/views/library_books/new.html.erb
<h1>New Library Book</h1>

<%= render 'form', library_book: @library_book %>

<%= link_to 'Back', library_books_path %>

app/views/library_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @library_book.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @library_book.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @library_book.description %>
</p>

<p>
  <strong>Status date:</strong>
  <%= @library_book.status_date %>
</p>

<p>
  <strong>Internal info:</strong>
  <%= @library_book.internal_info %>
</p>

<%= link_to 'Edit', edit_library_book_path(@library_book) %> |
<%= link_to 'Back', library_books_path %>